"""客服 Agent 状态、检查点与流程协调公共接口。"""

from app.agent.checkpoint import FileCheckpointStore
from app.agent.chat_runtime import ChatStateRuntime
from app.agent.coordinator import StateCoordinator
from app.agent.graph import build_unified_chat_graph
from app.agent.protocols import (
    AgentGraphError,
    AgentGraphExecutionError,
    AgentNode,
    AgentNodeExecutionError,
    ConditionalEdge,
)
from app.agent.runtime import AgentRuntime
from app.agent.state_mappers import qa_result_to_patch, rule_result_to_patch
from app.agent.state import (
    ActionStatus,
    AgentState,
    ChatSessionState,
    ChatTurnState,
    HumanState,
    LongTermMemoryState,
    MemorySnippet,
    NodeStatus,
    NodeTrace,
    PendingAction,
    ProductReference,
    ProductResolutionState,
    ResolvedProductContext,
    RetrievalContext,
    RetrievalEvidence,
    RetrievalState,
    ShortTermMemoryState,
    StateError,
    StateMessage,
    StatePatch,
    ToolDescriptor,
    ToolState,
    WorkflowState,
    WorkflowStatus,
)

__all__ = [
    "ActionStatus",
    "AgentGraphError",
    "AgentGraphExecutionError",
    "AgentNode",
    "AgentNodeExecutionError",
    "AgentRuntime",
    "AgentState",
    "ChatSessionState",
    "ChatStateRuntime",
    "ChatTurnState",
    "ConditionalEdge",
    "FileCheckpointStore",
    "HumanState",
    "LongTermMemoryState",
    "MemorySnippet",
    "NodeStatus",
    "NodeTrace",
    "PendingAction",
    "ProductReference",
    "ProductResolutionState",
    "ResolvedProductContext",
    "RetrievalContext",
    "RetrievalEvidence",
    "RetrievalState",
    "ShortTermMemoryState",
    "StateCoordinator",
    "StateError",
    "StateMessage",
    "StatePatch",
    "ToolDescriptor",
    "ToolState",
    "WorkflowState",
    "WorkflowStatus",
    "build_unified_chat_graph",
    "qa_result_to_patch",
    "rule_result_to_patch",
]
